name: corelab_app_challenge
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans/DMSans-VariableFont.ttf

    - family: DMSans-Light
      fonts:
        - asset: assets/fonts/DMSans/DMSans-Light.ttf

    - family: DMSans-Regular
      fonts:
        - asset: assets/fonts/DMSans/DMSans-Regular.ttf

    - family: DMSans-Medium
      fonts:
        - asset: assets/fonts/DMSans/DMSans-Medium.ttf
          style: normal

    - family: DMSans-Bold
      fonts:
        - asset: assets/fonts/DMSans/DMSans-Bold.ttf

    - family: DMSans-VariableFont
      fonts:
        - asset: assets/fonts/DMSans/DMSans-VariableFont.ttf